# -*- coding: utf-8 -*-
"""pytorch_book

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bvg9pNHjZyFNTBZuH3qEjB-I7bhFHiql
"""

import torch
import numpy as np

np.random.seed(420)
M = np.random.rand(10000, 10000)
Y = np.random.rand(10000, 1)

# Convert to tensors
M_t = torch.from_numpy(M)
M_y = torch.from_numpy(Y)

# Multiply by Itself
out = torch.mm(M_t, M_t)

# Find inverse
out = torch.inverse(M_t)

# Find betas of linear regression
out = torch.mm(
    torch.inverse(torch.mm(M_t.t(), M_t)),
    torch.mm(M_t.t(), M_y)
)

# Find eigenvalues and vectors
out = torch.eig(M_t)