# -*- coding: utf-8 -*-
"""tensor_book

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CnTf_C1cyOWbzkcDLkF2crKVe8PdNuAq
"""

import tensorflow as tf
import numpy as np

np.random.seed(420)
M = np.random.rand(10000, 10000)
Y = np.random.rand(10000, 1)

# Convert to tensor
M_t = tf.convert_to_tensor(M)
M_y = tf.convert_to_tensor(Y)

# Multiply tensors
out = tf.linalg.matmul(M_t, M_t)

# Find Inverse of tensors
out = tf.linalg.inv(M_t)

# Get betas for linear regression
out = tf.linalg.matmul(
    tf.linalg.inv(tf.linalg.matmul(tf.linalg.inv(M_t), M_t)),
    tf.linalg.matmul(tf.linalg.transpose(M_t), M_y)
)

# Get eigenvalues
out = tf.linalg.eigh(M_t)

